# Extra innehåll för undersidorna (påhittat testföretag).
SVC_MORE = {
"bostader": [
 ("Så bygger vi bostäder", ["Vi börjar alltid med frågan: vem ska bo här? En studentlägenhet, ett trygghetsboende och en familjebostad ställer helt olika krav på planlösning, förråd, ljud och utemiljö. Därför tar vi in synpunkter från förvaltare, hyresgästföreningar och framtida boende redan när vi skissar.",
   "Våra flerbostadshus byggs med prefabricerade väggelement och bjälklag i trä från vår egen fabrik. Elementen kommer till bygget med fönster och installationsdragningar på plats, vilket gör att huset blir tätt på några veckor. Det minskar risken för fukt och gör att invändiga arbeten kan börja tidigt.",
   "Vi har egna snickare, betongarbetare och arbetsledare på varje bygge. Installationer som el, VVS och ventilation gör vi tillsammans med lokala partner som vi har arbetat med i många år."]),
 ("Kvalitet du märker när du bor där", ["Vi lägger extra tid på det som syns och känns i vardagen: ljudisolering mellan lägenheterna, tysta ventilationsaggregat, rejäla förråd och trapphus med dagsljus. Varje lägenhet besiktigas av oss själva innan den slutliga besiktningen, och vi rättar fel innan någon flyttar in.",
   "Efter inflyttning har vi en egen garantiavdelning. Den som bor i ett hus vi har byggt kan ringa oss direkt under hela garantitiden på fem år."]),
 ("Upplåtelseformer vi bygger", ["Hyresrätter åt allmännyttan och privata fastighetsägare, bostadsrätter åt bostadsrättsföreningar och i egen regi, samt äganderätter i form av radhus och villor. Vi bygger också särskilda boenden: trygghetsboenden för äldre, LSS-boenden och studentbostäder."]),
 ("Vanliga frågor", ["<b>Hur lång tid tar det att bygga ett flerbostadshus?</b> Ett hus med 40 lägenheter tar ungefär 14 månader från byggstart till inflyttning. Projektering och bygglov tar oftast 6–12 månader innan dess.",
   "<b>Kan vi som beställare vara med och påverka?</b> Ja. I våra samverkansprojekt sitter beställaren med i projektgruppen från första skissen, och alla kostnader redovisas öppet.",
   "<b>Bygger ni i hela Sverige?</b> Nej, vi håller oss till Västsverige: Sjuhärad, Göteborgsregionen och Skaraborg. Då hinner vi alltid vara på plats."]),
],
"skolor": [
 ("Byggt för hur barn lär sig", ["En bra skola är inte bara en byggnad – den är en arbetsplats för hundratals barn och vuxna. Därför börjar vi varje skolprojekt med workshops tillsammans med rektorer, pedagoger, elevhälsa och ibland eleverna själva. Vi går igenom hur en vanlig dag ser ut: var barnen äter, var de vilar, var de hänger av sig och var det ofta blir trångt.",
   "Utifrån det planerar vi rum som går att använda på flera sätt, korta gångavstånd och tydliga entréer. Vi prioriterar dagsljus och god akustik, eftersom forskning visar att båda påverkar både koncentration och trivsel."]),
 ("Trä som stomme", ["De flesta av våra förskolor byggs med stomme i massivträ. Trä ger ett varmt och lugnt intryck, binder koldioxid och gör att bygget går fortare. Under byggtiden blir det också tystare och renare, vilket är viktigt när vi bygger intill en skola som är i drift.",
   "Vi använder giftfria material som är bedömda i Byggvarubedömningen eller Sunda Hus, och vi dokumenterar varje produkt i en loggbok som skolan får vid överlämningen."]),
 ("Bygga när skolan är igång", ["Ofta bygger vi ut eller om en skola samtidigt som undervisningen pågår. Då gör vi en särskild trygghetsplan tillsammans med skolan: inhägnade arbetsområden, separata vägar för byggtrafik, transporter utanför skoltider och bullriga arbeten under lov. Barnen får gärna komma på visning av bygget – med hjälm och väst."]),
 ("Det här ingår ofta", ["Matsal och tillagningskök, idrottshall, ateljéer och slöjdsalar, elevhälsa, personalrum, utemiljö med lekutrustning och odlingsytor, cykelparkering och hämtning- och lämningszoner."]),
],
"mark": [
 ("Allt under och runt huset", ["Innan ett hus kan byggas måste marken förberedas: träd och stubbar tas bort, marken schaktas, packas och dräneras, och vatten-, avlopps-, el- och fiberledningar dras fram. Lindvik Mark gör allt detta med egna maskiner och egen personal.",
   "Vi bygger också gator, vägar, rondeller, gång- och cykelvägar, parkeringsplatser, parker och lekplatser – både åt kommuner och åt privata beställare."]),
 ("Massor som stannar på plats", ["Det mest klimatsmarta schaktet är det som inte behöver köras bort. Vi gör en massbalans tidigt i varje projekt och planerar så att jord och sten kan återanvändas på plats, till exempel i vägbankar, bullervallar och terrassering. 2025 återanvände vi 71 % av alla massor i våra projekt.",
   "Det som ändå måste köras bort sorteras och lämnas till godkända mottagare. Vi provtar alltid marken innan schakt, så att förorenade massor hanteras rätt."]),
 ("Maskinpark", ["Vi har 64 egna maskiner: grävmaskiner från 2 till 45 ton, hjullastare, dumprar, vältar och lastbilar. 22 av maskinerna går på el eller HVO, och målet är att alla ska göra det till 2030. Alla förare har utbildning i säkerhet vid vägarbete."]),
 ("Exempel på uppdrag", ["Grundläggning för flerbostadshus och skolor, VA-ledningar i nya bostadsområden, ombyggnad av korsningar och rondeller, nya gång- och cykelvägar, dagvattendammar och översvämningsskydd, samt markarbeten för solcellsparker."]),
],
"trabyggnation": [
 ("Från skog till hus", ["Vi köper virke från skogar i Västra Götaland som är certifierade enligt FSC eller PEFC. I fabriken i Viskafors limmas brädorna ihop till skivor av korslimmat trä (KL-trä) och balkar av limträ. Skivorna sågas sedan till färdiga väggar och bjälklag med öppningar för fönster, dörrar och installationer.",
   "Allt görs inomhus, i rätt mått och utan väder och vind. När elementen kommer till bygget lyfts de på plats med kran och skruvas ihop. Ett hus med 40 lägenheter får sin stomme på ungefär sex veckor."]),
 ("Varför trä?", ["Trä binder koldioxid medan träden växer, och den stannar i huset så länge det står. En trästomme ger ungefär 40 % lägre klimatavtryck än en motsvarande stomme i betong.",
   "Trä är också lätt. Det gör att grunden kan bli mindre och att det går att bygga på mark som inte klarar tunga hus. På bygget blir det tystare, renare och torrare, och färre transporter behövs."]),
 ("Brand, ljud och fukt", ["Massivt trä förkolnar på ytan vid brand och skyddar då kärnan, så stommen behåller sin bärförmåga länge. Alla våra trähus dimensioneras enligt Boverkets brandkrav och kontrolleras av brandkonsult.",
   "För att få bra ljudisolering mellan lägenheter använder vi flytande golv och dubbla väggar. Mot fukt har vi ett fuktsäkerhetsprogram: elementen täcks under transport och montage, och vi mäter fukten i träet innan huset stängs."]),
 ("Klimatberäkning i varje projekt", ["Vi gör en klimatdeklaration för alla nya byggnader, som lagen kräver, men vi gör den redan i tidigt skede. Då kan vi jämföra olika lösningar och välja den som ger lägst utsläpp innan något är bestämt."]),
],
"byggservice": [
 ("Hjälp med det lilla – och lite större", ["Lindvik Service hjälper till med allt från en dörr som kärvar till ett helt nytt badrum. Vi har elva servicebilar med snickare, plattsättare och målare som utgår från Borås, Ulricehamn och Kinna. De flesta ärenden hinner vi titta på inom två arbetsdagar.",
   "Vi arbetar åt privatpersoner, bostadsrättsföreningar, fastighetsägare, skolor och företag."]),
 ("För dig som privatperson", ["Vi bygger om badrum och kök, lägger nya golv, bygger altaner och mindre tillbyggnader, byter fönster och dörrar och hjälper till efter vattenskador. Du får alltid ett skriftligt pris innan vi börjar, och du kan få ROT-avdrag på arbetskostnaden.",
   "Alla våra badrum byggs enligt branschreglerna Säker Vatteninstallation och GVK, och du får ett våtrumsintyg när jobbet är klart."]),
 ("Serviceavtal för fastighetsägare", ["Med ett serviceavtal får du en fast kontaktperson, prioriterad utryckning och ett fast pris per år för löpande underhåll. Vi gör också underhållsplaner så att du vet vad som behöver göras de kommande tio åren och vad det kommer att kosta."]),
 ("Så går det till", ["1. Du ringer eller skickar en förfrågan. 2. Vi kommer ut och tittar, oftast inom två arbetsdagar. 3. Du får ett skriftligt pris. 4. Vi gör jobbet och städar efter oss. 5. Vi går igenom resultatet tillsammans med dig."]),
],
"projektutveckling": [
 ("Från idé till kvarter", ["Projektutveckling handlar om att se möjligheter i en plats innan något är byggt. Vi letar efter mark där det behövs bostäder, lokaler eller service, och tar fram ett förslag på vad som skulle passa där – i dialog med kommunen, grannar och framtida användare.",
   "När vi har en idé ansöker vi om planbesked, tar fram en detaljplan tillsammans med kommunen och projekterar husen. Eftersom vi bygger själva kan vi tidigt räkna på vad husen kommer att kosta och se till att projektet blir möjligt att genomföra."]),
 ("Pågående områden", ["<b>Fristad Ängar, Borås:</b> 180 bostäder i radhus och mindre flerbostadshus, förskola och park. Byggstart 2027.",
   "<b>Hamnviken, Ulricehamn:</b> 240 bostäder vid Åsunden, med lokaler i bottenvåningarna. Detaljplanen beräknas vinna laga kraft 2027.",
   "<b>Kinna centrum:</b> 130 lägenheter, trygghetsboende och vårdcentral. Samråd pågår.",
   "<b>Sandared Station:</b> 100 bostäder nära pendeltåget. Planbesked beviljat 2026."]),
 ("Samarbete med kommunen", ["Vi tror på tidig dialog. Därför bjuder vi in till öppna möten, gör enkäter bland grannar och visar modeller och bilder av hur området kan bli. Synpunkterna tar vi med oss in i detaljplanen."]),
 ("Vill du sälja mark?", ["Äger du mark som kan passa för bostäder eller lokaler? Hör av dig, så gör vi en kostnadsfri bedömning av vad som skulle kunna byggas där."]),
],
}
SVC_STEPS = [("Första mötet","Vi lyssnar på vad du vill bygga, varför och när."),("Förslag och kalkyl","Vi tar fram skisser, tidplan och en öppen kalkyl."),("Projektering","Arkitekter och konstruktörer ritar klart, vi söker bygglov."),("Bygget","Egen personal på plats, veckomöten och tydlig rapportering."),("Överlämning och garanti","Besiktning, utbildning i huset och fem års garanti.")]

CO_MORE = {
"bostad": [("Bo hos oss",["Lindvik Bostad har 820 egna hyresrätter i Borås, Ulricehamn och Kinna. Alla lägenheter är byggda av Lindvik Bygg och förvaltas av vår egen personal. Vi har kontor i alla tre orterna och felanmälan dygnet runt.","Lediga lägenheter förmedlas via vår bostadskö. Det är gratis att stå i kön, och du förnyar din plats en gång per år."]),
 ("Köpa nyproducerat",["När vi säljer bostadsrätter eller radhus följer vi dig hela vägen: från första visningen och val av material till tillträde och garantibesiktning. Du får en egen kontaktperson som svarar på frågor under hela byggtiden.","Just nu säljer vi 18 radhus i Fristad Ängar, 4 rum och kök på 112 kvadratmeter med egen trädgård. Pris från 3 950 000 kronor."]),
 ("Hållbart boende",["Alla våra nya bostäder har solceller, laddplatser för elbil, cykelförråd med verkstad och gemensamma odlingslotter. Husen är byggda i trä och uppfyller kraven för Miljöbyggnad Silver."])],
"fastighet": [("Lokaler som växer med dig",["Lindvik Fastighet äger 40 000 kvadratmeter kontor, butiker, lager och samhällsfastigheter. Vi bygger om lokalerna när hyresgästernas behov ändras, med hjälp av Lindvik Byggs egna hantverkare.","De flesta av våra fastigheter ligger centralt i Borås och Ulricehamn, nära kollektivtrafik."]),
 ("Lediga lokaler",["Kontor, 240 m², Allégatan 14, Borås – ledigt från 1 mars 2027.","Butik, 180 m², Storgatan 8, Ulricehamn – ledigt nu.","Lager med kontor, 900 m², Viared, Borås – ledigt från 1 januari 2027."]),
 ("Gröna hyresavtal",["Alla nya hyresavtal är gröna. Det betyder att vi tillsammans med hyresgästen sätter mål för energi, avfall och resor, och följer upp dem varje år."])],
"mark": [("Om Lindvik Mark",["Lindvik Mark grundades 2004 när vi köpte vår första egna grävmaskin. Idag har bolaget 85 medarbetare och 64 maskiner och utför markarbeten åt kommuner, Trafikverket, privata beställare och Lindvik Byggs egna projekt."]),
 ("Det här gör vi",["Schakt och grundläggning, VA-ledningar, dagvattenlösningar, gator och vägar, rondeller, gång- och cykelvägar, parker och lekplatser, samt snöröjning och vinterväghållning i Borås."]),
 ("Säkerhet först",["Alla våra förare har utbildningen Arbete på väg och vi har haft noll allvarliga olyckor de senaste tre åren. Vi använder alltid trafikanordningsplaner och utbildad vakt när vi arbetar nära trafik."])],
"tra": [("Fabriken i Viskafors",["Fabriken invigdes 2019 och är 9 000 kvadratmeter stor. Den har en CNC-styrd sågstation för KL-trä, en limträlinje och en monteringshall där vi bygger färdiga väggelement med isolering, fönster och installationer.","Taket är täckt med 3 000 kvadratmeter solceller som ger ungefär hälften av fabrikens el."]),
 ("Kapacitet",["Vi förädlar 12 000 kubikmeter trä per år, vilket räcker till ungefär 500 lägenheter. Fabriken levererar till Lindvik Byggs egna projekt och till andra byggföretag i Västsverige."]),
 ("Besök fabriken",["Vi tar gärna emot studiebesök från skolor, kommuner och beställare. Kontakta oss så bokar vi en tid."])],
"service": [("Om Lindvik Service",["Lindvik Service har 32 medarbetare och elva servicebilar. Vi utgår från Borås, Ulricehamn och Kinna och hjälper till med reparationer, renoveringar och underhåll i hela Sjuhärad."]),
 ("ROT-avdrag",["När vi gör arbete i ditt hem kan du få ROT-avdrag på 30 % av arbetskostnaden, upp till 50 000 kronor per person och år. Vi sköter ansökan åt dig och drar av beloppet direkt på fakturan."]),
 ("Jour",["Vid akuta skador, som vattenläckor eller trasiga lås, har vi jour dygnet runt för fastighetsägare med serviceavtal."])],
}
PROJ_MORE = {
"ekbacken": [("Bakgrund",["Borås Stad behövde ersätta två äldre förskolor med fukt- och ventilationsproblem. Målet var en ny förskola med plats för 120 barn, nära skog och natur, som skulle vara klar till hösten 2026."]),
 ("Utmaningen",["Tomten sluttar kraftigt ner mot en bäck och har en gammal ekskog som skulle bevaras. Byggtrafiken fick inte störa grannskolan, och allt skulle stå klart på elva månader."]),
 ("Lösningen",["Vi placerade förskolan i två plan längs sluttningen, så att båda våningarna har egen entré direkt från marken. Stommen tillverkades i vår fabrik och monterades på fem veckor. Alla ekar utom en kunde sparas, och den som fälldes blev bänkar på gården."]),
 ("Hållbarhet",["Förskolan har solceller på taket, sedumtak som tar hand om regnvatten och är certifierad enligt Miljöbyggnad Guld. Klimatavtrycket blev 42 % lägre än för en motsvarande förskola i betong."]),
 ("Medverkande",["Beställare: Borås Stad. Arkitekt: Studio Ek (påhittat). Konstruktör: Trästrukturer AB (påhittat). Entreprenadform: samverkan, totalentreprenad."])],
"sjoglimten": [("Bakgrund",["Ulricehamns Bostäder ville bygga moderna hyresrätter med rimliga hyror nära centrum och sjön. Kvarteret skulle passa in bland de äldre villorna runt omkring."]),
 ("Lösningen",["Två huskroppar i fyra och fem våningar med fasader i trä och tegel. Lägenheterna är mellan ett och fyra rum, och alla har balkong eller uteplats mot söder eller sjön."]),
 ("Samverkan",["Projektet genomfördes i samverkan med öppna böcker. Beställare, arkitekt och Lindvik satt i samma projektgrupp från start, och slutkostnaden blev 3 % under budget."]),
 ("Fakta om husen",["64 lägenheter, 5 200 m² boarea, 52 kW solceller, 20 laddplatser, gemensam takterrass och cykelverkstad. Miljöbyggnad Silver."])],
"viskahallen": [("Bakgrund",["Föreningslivet i Viskafors hade länge saknat en fullstor hall. Den gamla gymnastiksalen var för liten för handboll och innebandy."]),
 ("Lösningen",["Hallen har ett spelplan på 40 × 20 meter som kan delas i tre salar med draperier. Taket bärs av 32 meter långa limträbalkar från vår egen fabrik några kilometer bort – så nära att de kunde transporteras utan eskort på natten."]),
 ("För hela orten",["Dagtid används hallen av skolan, kvällar och helger av sex föreningar. Läktaren har plats för 400 åskådare, och det finns ett kafé som drivs av föreningarna."])],
"rondell": [("Bakgrund",["Korsningen vid Hultafors hade många olyckor, särskilt med cyklister. Trafikverket och Bollebygds kommun beställde en ny rondell och en säker gång- och cykelväg."]),
 ("Utmaningen",["Vägen fick inte stängas, eftersom den är enda vägen till ett industriområde. Arbetet fick därför göras i fyra etapper med tillfälliga vägar."]),
 ("Resultat",["Rondellen öppnade två veckor före tidplan. Sedan dess har inga olyckor med personskador rapporterats i korsningen. Genom att återanvända massorna på plats sparade vi 900 lastbilstransporter."])],
}
NEWS_MORE = {
"ekbacken-pris": ["Priset delas ut varje år till en byggnad som gör Borås vackrare och bättre att leva i. I år fick juryn in 34 nomineringar.","I motiveringen skriver juryn att Ekbacken ”visar hur en förskola kan vara både varm, lugn och klimatsmart, och hur man kan bygga med respekt för platsen”.","Förskolan har funnits sedan augusti 2026 och har 120 barn. Personalen berättar att barnen redan har gett namn åt flera av ekarna på gården.","Ekbacken byggdes i samverkan mellan Borås Stad, arkitektkontoret och Lindvik Bygg. Stommen tillverkades i vår fabrik i Viskafors."],
"ny-vd": ["Lars Lindvik, som har lett företaget sedan 2012, blir arbetande styrelseordförande.","– Sara känner företaget, kunderna och medarbetarna bättre än någon annan. Hon är rätt person att ta oss in i nästa period, säger Lars Lindvik.","Sara Lindqvist är 44 år, utbildad högskoleingenjör och bor i Borås med sin familj. På fritiden tränar hon ett flicklag i fotboll.","Lindvik Bygg förblir familjeägt. Ägarstrukturen påverkas inte av vd-bytet."],
"goda-rad": ["Det här är råd vi ofta ger till privatpersoner som vill bygga eget hus. Har du frågor är du välkommen att ringa oss.","<b>Om budgeten:</b> Glöm inte kostnader som är lätta att missa: anslutningsavgifter för vatten och el, bygglovsavgift, kontrollansvarig, försäkring under byggtiden och trädgård.","<b>Om tomten:</b> Be om en geoteknisk undersökning. Lera eller berg kan göra grunden betydligt dyrare.","<b>Om tidplanen:</b> Räkna med 3–6 månader för bygglov och 6–9 månader för själva bygget av en villa."],
}
NEWS_EXTRA = [
 dict(slug="fabrik-solceller", title="Fabriken i Viskafors får nya solceller", date="2026-08-28", dtext="28 augusti 2026", img=21, short="3 000 kvadratmeter solceller ger hälften av fabrikens el.",
      body=["Nu är solcellerna på fabrikstaket i Viskafors klara. Anläggningen är på 600 kW och beräknas ge 550 000 kWh per år.","Det motsvarar ungefär hälften av fabrikens elbehov. Resten köps som förnybar el från vindkraft.","– Det känns rätt att trästommarna till våra hus nu tillverkas med el från solen, säger Maria Lind, chef för Lindvik Trä.","Solcellerna installerades av ett lokalt elföretag under fyra veckor i somras, utan att produktionen behövde stoppas."]),
 dict(slug="larlingar", title="20 nya lärlingar börjar hos oss", date="2026-08-18", dtext="18 augusti 2026", img=12, short="Rekordmånga unga börjar sin bana i byggbranschen hos Lindvik.", pos="50% 30%",
      body=["I augusti började 20 nya lärlingar på Lindvik Bygg – det största antalet någonsin. De flesta är snickare, men även betongarbetare, plattsättare och maskinförare finns med.","Varje lärling får en egen handledare och följer ett utbildningsprogram under två år. Efter godkänt yrkesbevis erbjuds alla som vill en fast anställning.","– Vi behöver fler unga i branschen, och det bästa sättet att lära sig är på riktigt, på ett riktigt bygge, säger HR-chefen Lina Öberg."]),
 dict(slug="fristad-angar", title="Försäljningen av radhus i Fristad Ängar har startat", date="2026-07-02", dtext="2 juli 2026", img=10, short="18 radhus med egen trädgård, inflyttning hösten 2027.", pos="50% 40%",
      body=["Nu kan du köpa radhus i första etappen av Fristad Ängar, ett nytt område med 180 bostäder norr om Borås.","Radhusen har fyra rum och kök på 112 kvadratmeter, egen trädgård och carport med laddbox. Pris från 3 950 000 kronor.","Området får en förskola, en park med lekplats och gångväg till pendeltåget. Byggstarten för första etappen är planerad till januari 2027.","Intresserad? Kontakta Lindvik Bostad för att boka visning av ritningar och material."]),
]

def _sec(inner, cls=""): return f'<section{(" class=" + chr(34) + cls + chr(34)) if cls else ""}><div class="in">{inner}</div></section>'
def _cols(items): return '<div class="cards3" style="margin-top:24px">' + "".join(f'<div class="person" style="gap:8px"><b style="font:700 1.15rem var(--display)">{h}</b><span style="font-size:15px;color:var(--muted);line-height:1.55">{t}</span></div>' for h, t in items) + "</div>"
EXTRA_PAGE = {
"tjanster.html": _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">En byggare för hela kedjan</h2><p>Lindvik Bygg är ett av få byggföretag i Västsverige som har hela kedjan i egen regi: projektutveckling, markarbeten, egen husfabrik, byggproduktion och service efter inflyttning. Det betyder färre överlämningar, kortare beslutsvägar och en kontakt som tar ansvar för helheten.</p><p>Vi bygger åt kommuner, bostadsbolag, fastighetsägare, företag och privatpersoner. Våra uppdrag sträcker sig från en ny dörr till ett helt nytt kvarter.</p><h2>Samverkan – vårt sätt att arbeta</h2><p>I de flesta större projekt arbetar vi i samverkan, även kallat partnering. Beställare, arkitekter, konstruktörer och vi sitter i samma projektgrupp från start. Alla kostnader redovisas öppet, och vi delar på både risker och besparingar. Resultatet blir färre överraskningar och bättre hus.</p><h2>Entreprenadformer</h2><ul><li><b>Totalentreprenad:</b> vi ansvarar för både projektering och byggande.</li><li><b>Utförandeentreprenad:</b> du står för ritningarna, vi bygger.</li><li><b>Samverkansentreprenad:</b> vi arbetar tillsammans med öppna kostnader.</li><li><b>Byggservice och ramavtal:</b> för löpande underhåll och mindre uppdrag.</li></ul></div><aside class="aside"><h3>Var bygger vi?</h3><p>Sjuhärad, Göteborgsregionen och Skaraborg. Vi har kontor i Borås, Ulricehamn, Kinna och Göteborg.</p><a class="btn btn-g" href="kontakt.html">Berätta om ditt projekt</a></aside></div>', "related") +
  _sec('<h2>Varför välja Lindvik?</h2>' + _cols([("Egen personal","240 egna medarbetare, varav 150 hantverkare. Vi vet vem som gör jobbet."),("Egen husfabrik","Trästommar från Viskafors ger kortare byggtid och lägre klimatavtryck."),("Lokalt sedan 1987","Vi bor där vi bygger och finns kvar efter att huset är klart."),("Öppna kostnader","I samverkansprojekt ser du alla kostnader, hela vägen."),("Fem års garanti","Egen garantiavdelning som svarar direkt när du ringer."),("Certifierade","ISO 9001, 14001 och 45001 för kvalitet, miljö och arbetsmiljö.")])),
"projekt.html": _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">Byggt i Västsverige sedan 1987</h2><p>Sedan starten har vi byggt över 1 100 projekt: bostäder, förskolor och skolor, idrottshallar, kontor, vägar och parker. Här visar vi några av de senaste. Fler referenser skickar vi gärna om du hör av dig.</p><p>Varje projekt följs upp med en enkät till beställaren och en genomgång i projektgruppen. Det vi lär oss tar vi med oss till nästa bygge. 2025 fick vi i snitt 4,6 av 5 i nöjdhet från våra beställare.</p><h2>Projekt per år</h2><ul><li>2025: 42 avslutade projekt, varav 9 större än 50 miljoner kronor.</li><li>2024: 39 avslutade projekt.</li><li>2023: 36 avslutade projekt.</li></ul></div><aside class="aside"><h3>Vill du se ett projekt på plats?</h3><p>Vi visar gärna färdiga hus och pågående byggen för beställare och studenter.</p><a class="btn btn-g" href="kontakt.html">Boka ett besök</a></aside></div>', "related"),
"nyheter.html": _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">För journalister</h2><p>Vill du skriva om ett av våra projekt, intervjua någon av oss eller använda bilder? Hör av dig till vår presstjänst så hjälper vi till. Vi svarar alltid samma dag.</p><p>Pressbilder på ledning, projekt och fabriken finns att låna kostnadsfritt. Ange fotograf när du publicerar.</p></div><aside class="aside"><h3>Presskontakt</h3><dl><div><dt>Namn</dt><dd>Elin Strand, kommunikationschef</dd></div><div><dt>Telefon</dt><dd>033-20 40 79</dd></div><div><dt>Mejl</dt><dd>press@lindvikbygg.se</dd></div></dl></aside></div>', "related"),
"om-oss.html": _sec('<h2>Våra kontor</h2>' + _cols([("Borås","Huvudkontor med 120 medarbetare. Här finns ledning, ekonomi, inköp och projektering."),("Ulricehamn","Kontor för bostäder och service i östra Sjuhärad, 45 medarbetare."),("Kinna","Lindvik Mark och service för Marks kommun, 50 medarbetare."),("Göteborg","Projektutveckling och anbud för Göteborgsregionen, 25 medarbetare.")]), "related") +
  _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">Ägare och organisation</h2><p>Lindvik Bygg ägs av familjen Lindvik genom Lindvik Invest AB. Koncernen består av moderbolaget Lindvik Bygg AB och fem dotterbolag: Lindvik Bostad, Lindvik Fastighet, Lindvik Mark, Lindvik Trä och Lindvik Service.</p><p>Vi har ingen extern ägare och inga planer på att sälja. Det ger oss möjlighet att tänka långsiktigt, till exempel när vi investerar i utbildning, maskiner och fabriken.</p><h2>Lokalt engagemang</h2><p>Vi sponsrar 14 idrottsföreningar i Sjuhärad, framför allt barn- och ungdomsverksamhet. Varje år tar vi emot 40 praoelever och samarbetar med byggprogrammen på tre gymnasieskolor.</p><h2>Samarbetspartner</h2><p>Vi arbetar med ett fast nätverk av lokala installatörer, arkitekter och konstruktörer. Många av samarbetena har pågått i mer än tio år.</p></div><aside class="aside"><h3>Nyckeltal 2025</h3><dl><div><dt>Omsättning</dt><dd>1,1 miljarder kronor</dd></div><div><dt>Rörelseresultat</dt><dd>58 miljoner kronor</dd></div><div><dt>Soliditet</dt><dd>41 %</dd></div><div><dt>Sjukfrånvaro</dt><dd>3,2 %</dd></div></dl></aside></div>'),
"hallbarhet.html": _sec('<h2>Tre områden vi mäter</h2>' + _cols([("Klimat och miljö","Utsläpp per kvadratmeter, andel trä, återanvända massor, sorterat avfall och fossilfria maskiner."),("Människor","Olyckor, sjukfrånvaro, lärlingar, medarbetarnöjdhet och jämställdhet."),("Ekonomi","Lönsamhet, lokala inköp och betalning till leverantörer i tid.")]), "related") +
  _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">Klimat</h2><p>Det mesta av ett hus klimatavtryck uppstår när material tillverkas, särskilt betong och stål. Därför är vårt viktigaste verktyg att bygga mer i trä och att använda betong med lägre klimatpåverkan där vi behöver betong. Sedan 2020 har vi minskat utsläppen per kvadratmeter med 38 %.</p><p>Vi klimatberäknar alla projekt i tidigt skede, så att vi kan välja bättre lösningar innan något är bestämt. Våra arbetsmaskiner går i allt högre grad på el och HVO, och fabriken drivs delvis med solel.</p><h2>Människor</h2><p>Alla som arbetar på våra byggen ska komma hem lika friska som de kom. Vi har säkerhetsgenomgång varje morgon, och alla kan stoppa arbetet om något känns osäkert. 2025 hade vi inga allvarliga olyckor.</p><p>Vi vill också att fler unga och fler kvinnor ska välja byggbranschen. 18 % av våra nyanställda 2025 var kvinnor, och vi har 20 lärlingar i år.</p><h2>Krav på leverantörer</h2><p>Alla leverantörer skriver under vår uppförandekod om arbetsvillkor, miljö och antikorruption. Vi kontrollerar regelbundet att underentreprenörer betalar skatter och har kollektivavtal.</p><h2>Certifieringar</h2><ul><li>ISO 9001 – kvalitet</li><li>ISO 14001 – miljö</li><li>ISO 45001 – arbetsmiljö</li><li>Licens för Svanenmärkta hus</li></ul></div><aside class="aside"><h3>Mål och utfall</h3><dl><div><dt>Klimat per m², mål 2030</dt><dd>−50 % (utfall −38 %)</dd></div><div><dt>Sorterat avfall, mål</dt><dd>90 % (utfall 92 %)</dd></div><div><dt>Fossilfria maskiner, mål 2030</dt><dd>100 % (utfall 34 %)</dd></div><div><dt>Lärlingar per år, mål</dt><dd>20 (utfall 20)</dd></div></dl></aside></div>'),
"jobb.html": _sec('<h2>Så går rekryteringen till</h2><ol class="timeline"><li><b>Ansökan</b><p>Skicka CV och några rader om dig själv. Personligt brev är inte nödvändigt.</p></li><li><b>Första samtal</b><p>Vi ringer inom en vecka och pratar om jobbet och dina förväntningar.</p></li><li><b>Intervju och platsbesök</b><p>Du träffar din blivande chef och några kollegor, gärna ute på ett bygge.</p></li><li><b>Referenser och erbjudande</b><p>Vi tar referenser och ger besked senast två veckor efter intervjun.</p></li><li><b>Introduktion</b><p>Första veckan går du en introduktion med säkerhet, verktyg och en fadder.</p></li></ol>', "related") +
  _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">Röster från medarbetare</h2><p><i>”Jag började som lärling 2017 och är arbetsledare idag. Här får man chansen om man vill.”</i> – Ahmed, arbetsledare i Borås</p><p><i>”Det bästa är att vi bygger i trä. Det är tyst, rent och man ser huset växa varje dag.”</i> – Emma, montör på Lindvik Trä</p><p><i>”Jag har kört maskin i 25 år. Här har vi bra maskiner och chefer som lyssnar.”</i> – Göran, maskinförare i Kinna</p><h2>Förmåner</h2><ul><li>Kollektivavtal, tjänstepension och sjukvårdsförsäkring</li><li>Friskvårdsbidrag på 5 000 kronor per år</li><li>Arbetskläder och verktyg</li><li>Vinstdelning för alla anställda</li><li>Personalfester, fiskeresa och julbord</li></ul><h2>Utveckling</h2><p>Alla medarbetare har ett utvecklingssamtal per år och en egen utbildningsplan. Vi har ett eget ledarskapsprogram för blivande arbetsledare och platschefer.</p></div><aside class="aside"><h3>Kontakt HR</h3><dl><div><dt>Namn</dt><dd>Lina Öberg, HR-chef</dd></div><div><dt>Telefon</dt><dd>033-20 40 80</dd></div><div><dt>Mejl</dt><dd>jobb@lindvikbygg.se</dd></div></dl></aside></div>'),
"kontakt.html": _sec('<div class="content"><div class="prose"><h2 style="margin-top:0">Öppettider</h2><ul><li>Kundtjänst: vardagar 07–16</li><li>Felanmälan för hyresgäster: dygnet runt via telefon</li><li>Jour för serviceavtal: dygnet runt</li></ul><h2>Garanti och reklamation</h2><p>Har du upptäckt ett fel i ett hus vi har byggt? Kontakta vår garantiavdelning på garanti@lindvikbygg.se eller 033-20 40 77. Beskriv felet och skicka gärna bilder. Vi hör av oss inom tre arbetsdagar.</p><h2>För leverantörer</h2><p>Vill du bli leverantör eller underentreprenör? Skicka en presentation till inkop@lindvikbygg.se. Alla leverantörer behöver skriva under vår uppförandekod.</p><h2>Hitta till huvudkontoret</h2><p>Huvudkontoret ligger på Allégatan 12 i centrala Borås, fem minuters promenad från resecentrum. Besöksparkering finns på gården, infart från Allégatan.</p></div><aside class="aside"><h3>Snabbnummer</h3><dl><div><dt>Kundtjänst</dt><dd>033-20 40 60</dd></div><div><dt>Garanti</dt><dd>033-20 40 77</dd></div><div><dt>Lindvik Service</dt><dd>033-20 40 75</dd></div><div><dt>Press</dt><dd>033-20 40 79</dd></div></dl></aside></div>'),
}

# ---- påfyllning ----
for k, extra in {
 "bostad": [("Så söker du lägenhet", ["Registrera dig i bostadskön på vår webbplats eller på något av våra kontor. När en lägenhet blir ledig skickar vi erbjudande till de som har stått längst i kön och uppfyller kraven. Du behöver ha en inkomst som är minst tre gånger hyran och inga betalningsanmärkningar.", "Visning sker oftast inom en vecka efter erbjudandet, och kontraktet skrivs digitalt med BankID."]),
            ("Hyresgäst hos oss", ["Som hyresgäst har du en egen bovärd som du träffar i området. Felanmälan görs via app, webb eller telefon dygnet runt. Vi har som mål att åtgärda vanliga fel inom fem arbetsdagar.", "Varje år gör vi en enkät bland våra hyresgäster. 2025 svarade 87 % att de skulle rekommendera oss som hyresvärd."])],
 "fastighet": [("Våra fastigheter", ["Kvarteret Allén i Borås: 14 000 m² kontor och butiker, byggt 1962 och totalrenoverat 2021.", "Viared Logistik: 12 000 m² lager och lätt industri, byggt 2016.", "Storgatan 8 i Ulricehamn: 4 500 m² butiker, kontor och 24 lägenheter.", "Skolan Solgläntan i Kinna: 6 000 m² som hyrs ut till Marks kommun på 25 år."]),
               ("Förvaltning", ["Vi har egna fastighetstekniker som känner husen. De sköter löpande underhåll, styr värme och ventilation och är hyresgästernas första kontakt. Energianvändningen i våra fastigheter har minskat med 24 % sedan 2018."])],
 "mark": [("Kunder", ["Våra största kunder är Borås Stad, Trafikverket, Ulricehamns kommun och Marks kommun. Vi utför också markarbeten åt industrier, energibolag och Lindvik Byggs egna projekt."]),
          ("Vinterväghållning", ["Under vintern plogar och sandar vi 140 kilometer väg och 60 parkeringsplatser i Borås. Vi har beredskap dygnet runt från november till mars."])],
 "tra": [("Så tillverkas en vägg", ["1. Virket torkas till rätt fukthalt och sorteras efter hållfasthet. 2. Brädorna limmas i korsvisa lager till stora skivor. 3. Skivorna sågas till väggar med CNC-maskin, med öppningar för fönster och installationer. 4. Isolering, fönster och fasadskiva monteras i hallen. 5. Väggarna märks, plastas in och lastas i rätt ordning för montage på bygget."]),
         ("Medarbetare", ["I fabriken arbetar 45 personer: maskinoperatörer, montörer, konstruktörer och logistikpersonal. Vi arbetar i två skift och har låg ljudnivå och bra ventilation i hallen."])],
 "service": [("Vanliga uppdrag", ["Badrumsrenoveringar, köksbyten, golvläggning, fönsterbyten, altaner och plank, takarbeten, fuktskador och vattenskador, tillgänglighetsanpassning och mindre ombyggnader i kontor och skolor."]),
             ("Det här säger våra kunder", ["<i>”Snabba, noggranna och trevliga. Badrummet blev klart på den dag de lovade.”</i> – Kund i Borås, 2026", "<i>”Vi har serviceavtal för våra tre fastigheter och har alltid någon att ringa.”</i> – Bostadsrättsförening i Ulricehamn"])],
}.items(): CO_MORE[k] += extra
for k, extra in {
 "ekbacken": [("Tidslinje", ["Mars 2025: Byggstart. April 2025: Grunden gjuten. Maj 2025: Stommen monterad på fem veckor. Juni 2025: Taket tätt. Februari 2026: Utemiljön klar. Augusti 2026: Barnen flyttar in."]), ("Röster om projektet", ["<i>”Det märks att man har lyssnat på oss som jobbar här. Rummen fungerar som vi ville.”</i> – Förskolechef, Ekbacken"])],
 "sjoglimten": [("Tidslinje", ["Januari 2024: Byggstart. Mars 2024: Stommen till hus 1 monterad. Juni 2024: Stommen till hus 2 monterad. December 2024: Inflyttning hus 1. Mars 2025: Inflyttning hus 2."]), ("Röster om projektet", ["<i>”Samverkan gjorde att vi kunde fatta beslut tidigt och hålla budget.”</i> – Projektchef, Ulricehamns Bostäder"])],
 "viskahallen": [("Tidslinje", ["September 2024: Byggstart. November 2024: Limträbalkarna lyfts på plats. Mars 2025: Hallgolvet lagt. Augusti 2025: Invigning med handbollsmatch."]), ("Hållbarhet", ["Hallen värms med bergvärme och har LED-belysning som styrs efter dagsljuset. Taket har solceller på 80 kW."])],
 "rondell": [("Tidslinje", ["Mars 2024: Etapp 1, tillfällig väg. Maj 2024: Etapp 2, ny rondell norra halvan. Juli 2024: Etapp 3, södra halvan. September 2024: Etapp 4, gång- och cykelväg och belysning. Oktober 2024: Klart."]), ("Röster om projektet", ["<i>”Trafiken flöt hela tiden, och informationen till oss som bor här var tydlig.”</i> – Boende i Hultafors"])],
}.items(): PROJ_MORE[k] += extra
for n in NEWS_EXTRA:
    n["body"] += ["Lindvik Bygg är ett familjeägt bygg- och anläggningsföretag i Västsverige med 240 medarbetare och kontor i Borås, Ulricehamn, Kinna och Göteborg.", "För mer information, kontakta presstjänsten på press@lindvikbygg.se eller 033-20 40 79."]
